### ISSUE TITLE
Vehicle renderer

### ISSUE THREAD

**Issue by Waltharnack** [Laykel/heigvd-pro-a-02-SiTR#70]

**Comment by Waltharnack** [comment]
We discussed if the vehicle should draw himself.
It seems that a vehicle should have a "render description" and the renderer then draw them. See : [https://gamedev.stackexchange.com/questions/14133/should-actors-in-a-game-be-responsible-for-drawing-themselves](https://gamedev.stackexchange.com/questions/14133/should-actors-in-a-game-be-responsible-for-drawing-themselves)

**Comment by Laykel** [comment]
First version implemented in #95
