### ISSUE TITLE
Is it necessary to return a list of string in enum?

### ISSUE THREAD

**Issue by texx94** [Laykel/heigvd-pro-a-02-SiTR#84]
What GUI team need is just a toString because of the public visibility of Enum. So in order to set our GUI we just make :

```
for (VehicleBehaviourType vb : VehicleBehaviourType.values()) {
    // call toString for each object
    behaviorSelector.addItem(vb);
}
```

**Comment by Laykel** [comment]
Good point, these methods are just poorly thought out. This will be fixed in the next PR.
